package com.lilac.anime.data.subtitle

import com.lilac.anime.*
import com.lilac.anime.cast.*
import com.lilac.anime.core.model.*
import com.lilac.anime.core.update.*
import com.lilac.anime.data.*
import com.lilac.anime.data.matcher.*
import com.lilac.anime.data.offline.*
import com.lilac.anime.network.*
import com.lilac.anime.player.*
import com.lilac.anime.ui.*
import com.lilac.anime.ui.detail.*
import com.lilac.anime.ui.home.*
import com.lilac.anime.ui.navigation.*
import com.lilac.anime.ui.search.*
import com.lilac.anime.ui.settings.*
import com.lilac.anime.ui.theme.*
import com.lilac.anime.viewmodel.*

import android.content.Context
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File

object SubtitleStore {
    private const val PREF_NAME = "lilac_subtitle_store"
    private const val IGNORED_PREFIX = "ignored_"
    private const val FONT_PATH_PREFIX = "font_path_"
    private const val FONT_SOURCE_PREFIX = "font_source_"
    private const val ALL_PATHS_PREFIX = "all_paths_"
    private const val DISPLAY_NAME_PREFIX = "display_name_"
    private val SUPPORTED_SUBTITLE_EXTENSIONS = setOf(
        "ass", "ssa", "srt", "vtt", "smi", "sami",
        "sub", "mpl2", "mpsub", "jacosub", "aqt", "pjs", "rt", "sbv"
    )

    data class SavedSubtitle(
        val source: String,
        val path: String,
        val ignored: Boolean,
        val episodeMatch: Boolean,
        val displayName: String = ""
    )

    /**
     * The filename generated by SubtitleDownloader is the authoritative episode
     * identity for Linkkf VTT files: sub_<animeId>_ep_<episodeKey>.vtt
     *
     * This is deliberately based on the generated filename rather than subtitle
     * contents or the remote VTT URL. A Linkkf VTT can have no useful episode
     * metadata, while its download request already knows the exact display key.
     */
    fun pathMatchesEpisode(path: String, episodeNumber: Int): Boolean {
        val file = File(path)
        if (!file.isFile || episodeNumber <= 0) return false
        val name = file.nameWithoutExtension.lowercase(java.util.Locale.ROOT)
        name.toIntOrNull()?.let { return it == episodeNumber }
        Regex("^ep_([a-z0-9._-]+)_([a-f0-9]{8,64})$", RegexOption.IGNORE_CASE)
            .find(name)?.groupValues?.getOrNull(1)?.toIntOrNull()?.let { return it == episodeNumber }
        Regex("(?:^|_)ep_([a-z0-9._-]+?)(?:_(?:linkkf|reanime))?$", RegexOption.IGNORE_CASE)
            .find(name)?.groupValues?.getOrNull(1)?.toIntOrNull()?.let { return it == episodeNumber }
        Regex("_(\\d{1,3})_(?:direct|archive)(?:_|$)", RegexOption.IGNORE_CASE)
            .find(name)?.groupValues?.getOrNull(1)?.toIntOrNull()?.let { return it == episodeNumber }
        return SubtitleEpisodeMatcher.matches(name, episodeNumber)
    }

    /**
     * Episode-key-aware matching. For the newly generated Linkkf VTT filename,
     * the exact key after `_ep_` wins. This keeps 4, 4a, 04, etc. from being
     * accidentally treated as the same subtitle when the source distinguishes them.
     */
    fun subtitleMatchesEpisode(path: String, episodeKey: String, episodeNumber: Int): Boolean {
        val file = File(path)
        if (!file.isFile || episodeNumber <= 0) return false
        val name = file.nameWithoutExtension.lowercase(java.util.Locale.ROOT)
        val normalizedKey = safeEpisodeKey(episodeKey)

        // Jimaku cache format: ep_<episodeKey>_<urlHash>.<ext>.
        Regex("^ep_([a-z0-9._-]+)_([a-f0-9]{8,64})$", RegexOption.IGNORE_CASE)
            .find(name)?.groupValues?.getOrNull(1)?.let { generatedKey ->
                return generatedKey == normalizedKey
            }

        Regex("(?:^|_)ep_([a-z0-9._-]+?)(?:_(?:linkkf|reanime))?$", RegexOption.IGNORE_CASE)
            .find(name)?.groupValues?.getOrNull(1)?.let { generatedKey ->
                return generatedKey == normalizedKey
            }

        // Non-Linkkf/legacy subtitle files use the existing numeric/header checks.
        if (!pathMatchesEpisode(path, episodeNumber)) return false
        return subtitleMatchesEpisode(path, episodeNumber)
    }

    private fun safeEpisodeKey(episodeKey: String): String = episodeKey.lowercase(java.util.Locale.ROOT).replace(Regex("[^a-z0-9._-]"), "_")
    private fun key(animeId: String, episodeKey: String, source: String) = "${animeId}_${safeEpisodeKey(episodeKey)}_$source"
    private fun key(animeId: String, episodeNumber: Int, source: String) = key(animeId, episodeNumber.toString(), source)
    private fun fontPathKey(animeId: String, source: String) = FONT_PATH_PREFIX + "${animeId}_$source"
    private fun fontSourceKey(animeId: String, source: String) = FONT_SOURCE_PREFIX + "${animeId}_$source"
    private fun allPathsKey(animeId: String, episodeKey: String, source: String) = ALL_PATHS_PREFIX + key(animeId, episodeKey, source)

    fun subtitleMatchesEpisode(path: String, episodeNumber: Int): Boolean {
        if (!pathMatchesEpisode(path, episodeNumber)) return false
        val file = File(path)
        if (!file.isFile || episodeNumber <= 0) return false
        val ext = file.extension.lowercase(java.util.Locale.ROOT)
        if (ext !in setOf("ass", "ssa")) return true
        return try {
            val text = file.inputStream().bufferedReader().use { it.readText().take(120_000) }
            val header = text.lineSequence()
                .takeWhile { !it.trim().equals("[Events]", true) }
                .filter {
                    val t = it.trimStart()
                    t.startsWith("Title:", true) || t.startsWith("Original Script:", true) ||
                        t.startsWith("Comment:", true) || t.startsWith("Notes:", true)
                }.joinToString(" ")
            if (header.isBlank()) return true
            SubtitleEpisodeMatcher.parse(header)?.episode?.let { it == episodeNumber } ?: true
        } catch (_: Exception) { true }
    }

    suspend fun save(context: Context, animeId: String, episodeKey: String, episodeNumber: Int, source: String, path: String?, displayName: String? = null) = withContext(Dispatchers.IO) {
        val prefs = context.getSharedPreferences(PREF_NAME, Context.MODE_PRIVATE)
        val primaryKey = key(animeId, episodeKey, source)
        val allKey = allPathsKey(animeId, episodeKey, source)
        val existing = prefs.getStringSet(allKey, emptySet()).orEmpty().toMutableSet()
        if (path.isNullOrBlank()) {
            prefs.edit().remove(primaryKey).remove(allKey).remove(ignoredKey(animeId, episodeKey, source)).apply()
        } else {
            existing.add(path)
            val edit = prefs.edit().putString(primaryKey, path).putStringSet(allKey, existing)
                .remove(ignoredKey(animeId, episodeKey, source))
            if (!displayName.isNullOrBlank()) edit.putString(displayNameKey(path), displayName.trim())
            edit.apply()
        }
    }

    /** Persist every subtitle asset discovered for this episode while keeping [primaryPath] as the default. */
    suspend fun saveAll(
        context: Context, animeId: String, episodeKey: String, episodeNumber: Int,
        source: String, paths: Collection<String>, primaryPath: String? = paths.firstOrNull()
    ) = withContext(Dispatchers.IO) {
        val valid = paths.filter { it.isNotBlank() && File(it).isFile }.distinct()
        val prefs = context.getSharedPreferences(PREF_NAME, Context.MODE_PRIVATE)
        val primaryKey = key(animeId, episodeKey, source)
        val allKey = allPathsKey(animeId, episodeKey, source)
        if (valid.isEmpty()) {
            prefs.edit().remove(primaryKey).remove(allKey).apply()
        } else {
            val primary = primaryPath?.takeIf { it in valid } ?: valid.first()
            prefs.edit().putString(primaryKey, primary).putStringSet(allKey, valid.toSet())
                .remove(ignoredKey(animeId, episodeKey, source)).apply()
        }
    }

    suspend fun get(context: Context, animeId: String, episodeKey: String, episodeNumber: Int, source: String): String? = withContext(Dispatchers.IO) {
        val prefs = context.getSharedPreferences(PREF_NAME, Context.MODE_PRIVATE)
        val k = key(animeId, episodeKey, source)
        val path = prefs.getString(k, null) ?: return@withContext null
        if (prefs.getBoolean(ignoredKey(animeId, episodeKey, source), false)) return@withContext null
        if (subtitleMatchesEpisode(path, episodeKey, episodeNumber)) return@withContext path
        prefs.edit().remove(k).remove(ignoredKey(animeId, episodeKey, source)).apply()
        File(path).takeIf(File::isFile)?.delete()
        null
    }

    suspend fun list(context: Context, animeId: String, episodeKey: String, episodeNumber: Int): List<SavedSubtitle> = withContext(Dispatchers.IO) {
        val prefs = context.getSharedPreferences(PREF_NAME, Context.MODE_PRIVATE)
        listOf("linkkf", "reanime", "jimaku", "kairan", "csora").flatMap { source ->
            val primary = prefs.getString(key(animeId, episodeKey, source), null)
            val stored = prefs.getStringSet(allPathsKey(animeId, episodeKey, source), emptySet()).orEmpty()
            val paths = (stored + listOfNotNull(primary)).distinct()
            val ignored = prefs.getBoolean(ignoredKey(animeId, episodeKey, source), false)
            paths.mapNotNull { path ->
                if (!File(path).isFile) null
                else SavedSubtitle(source, path, ignored, subtitleMatchesEpisode(path, episodeKey, episodeNumber), prefs.getString(displayNameKey(path), File(path).name).orEmpty())
            }
        }
    }

    /** User-imported subtitles are stored separately from downloaded/remote subtitle sources. */
    suspend fun listUser(
        context: Context, animeId: String, episodeKey: String, episodeNumber: Int
    ): List<SavedSubtitle> = withContext(Dispatchers.IO) {
        val prefs = context.getSharedPreferences(PREF_NAME, Context.MODE_PRIVATE)
        val source = "user"
        val primary = prefs.getString(key(animeId, episodeKey, source), null)
        val stored = prefs.getStringSet(allPathsKey(animeId, episodeKey, source), emptySet()).orEmpty()
        val paths = (stored + listOfNotNull(primary)).distinct()
        val ignored = prefs.getBoolean(ignoredKey(animeId, episodeKey, source), false)
        paths.mapNotNull { path ->
            if (!File(path).isFile) null
            else SavedSubtitle(source, path, ignored, subtitleMatchesEpisode(path, episodeKey, episodeNumber), prefs.getString(displayNameKey(path), File(path).name).orEmpty())
        }
    }

    suspend fun getUser(context: Context, animeId: String, episodeKey: String, episodeNumber: Int): String? =
        get(context, animeId, episodeKey, episodeNumber, "user")

    suspend fun setIgnored(context: Context, animeId: String, episodeKey: String, episodeNumber: Int, source: String, ignored: Boolean) = withContext(Dispatchers.IO) {
        context.getSharedPreferences(PREF_NAME, Context.MODE_PRIVATE).edit().putBoolean(ignoredKey(animeId, episodeKey, source), ignored).apply()
    }

    suspend fun deleteOne(
        context: Context, animeId: String, episodeKey: String, episodeNumber: Int, source: String, path: String
    ) = withContext(Dispatchers.IO) {
        val prefs = context.getSharedPreferences(PREF_NAME, Context.MODE_PRIVATE)
        val primaryKey = key(animeId, episodeKey, source)
        val allKey = allPathsKey(animeId, episodeKey, source)
        val stored = prefs.getStringSet(allKey, emptySet()).orEmpty().toMutableSet()
        stored.remove(path)
        val primary = prefs.getString(primaryKey, null)
        val nextPrimary = if (primary == path) stored.firstOrNull() else primary
        prefs.edit().apply {
            if (nextPrimary.isNullOrBlank()) remove(primaryKey) else putString(primaryKey, nextPrimary)
            if (stored.isEmpty()) remove(allKey) else putStringSet(allKey, stored)
        }.apply()
        prefs.edit().remove(displayNameKey(path)).apply()
        File(path).takeIf(File::isFile)?.delete()
    }

    suspend fun delete(context: Context, animeId: String, episodeKey: String, episodeNumber: Int, source: String) = withContext(Dispatchers.IO) {
        val prefs = context.getSharedPreferences(PREF_NAME, Context.MODE_PRIVATE)
        val k = key(animeId, episodeKey, source)
        val paths = prefs.getStringSet(allPathsKey(animeId, episodeKey, source), emptySet()).orEmpty() +
            listOfNotNull(prefs.getString(k, null))
        prefs.edit().remove(k).remove(allPathsKey(animeId, episodeKey, source)).remove(ignoredKey(animeId, episodeKey, source)).apply()
        paths.forEach { path ->
            prefs.edit().remove(displayNameKey(path)).apply()
            File(path).takeIf(File::isFile)?.delete()
        }
    }

    fun getSelectedFont(context: Context, animeId: String, source: String): String? =
        context.getSharedPreferences(PREF_NAME, Context.MODE_PRIVATE)
            .getString(fontPathKey(animeId, source), null)
            ?.takeIf { File(it).isFile }

    fun saveSelectedFont(context: Context, animeId: String, source: String, path: String?) {
        context.getSharedPreferences(PREF_NAME, Context.MODE_PRIVATE).edit()
            .apply {
                if (path.isNullOrBlank()) remove(fontPathKey(animeId, source))
                else putString(fontPathKey(animeId, source), path)
                putString(fontSourceKey(animeId, source), source)
            }.apply()
    }

    fun clearSelectedFont(context: Context, animeId: String, source: String) {
        context.getSharedPreferences(PREF_NAME, Context.MODE_PRIVATE).edit()
            .remove(fontPathKey(animeId, source))
            .remove(fontSourceKey(animeId, source))
            .apply()
    }
    fun setDisplayName(context: Context, path: String, displayName: String?) {
        val prefs = context.getSharedPreferences(PREF_NAME, Context.MODE_PRIVATE)
        prefs.edit().apply {
            if (displayName.isNullOrBlank()) remove(displayNameKey(path))
            else putString(displayNameKey(path), displayName.trim())
        }.apply()
    }

    fun getDisplayName(context: Context, path: String): String =
        context.getSharedPreferences(PREF_NAME, Context.MODE_PRIVATE)
            .getString(displayNameKey(path), null)
            ?.takeIf { it.isNotBlank() }
            ?: File(path).name

    private fun displayNameKey(path: String): String = DISPLAY_NAME_PREFIX + path
    private fun ignoredKey(animeId: String, episodeNumber: Int, source: String) = IGNORED_PREFIX + key(animeId, episodeNumber, source)
    private fun ignoredKey(animeId: String, episodeKey: String, source: String) = IGNORED_PREFIX + key(animeId, episodeKey, source)

    suspend fun save(context: Context, animeId: String, episodeNumber: Int, source: String, path: String?) =
        save(context, animeId, episodeNumber.toString(), episodeNumber, source, path)

    suspend fun get(context: Context, animeId: String, episodeNumber: Int, source: String): String? = withContext(Dispatchers.IO) {
        val prefs = context.getSharedPreferences(PREF_NAME, Context.MODE_PRIVATE)
        val k = key(animeId, episodeNumber, source)
        val path = prefs.getString(k, null) ?: return@withContext null
        if (prefs.getBoolean(ignoredKey(animeId, episodeNumber, source), false)) return@withContext null
        if (subtitleMatchesEpisode(path, episodeNumber)) return@withContext path
        prefs.edit().remove(k).remove(ignoredKey(animeId, episodeNumber, source)).apply()
        File(path).takeIf(File::isFile)?.delete()
        null
    }

    suspend fun list(context: Context, animeId: String, episodeNumber: Int): List<SavedSubtitle> =
        list(context, animeId, episodeNumber.toString(), episodeNumber)

    suspend fun setIgnored(context: Context, animeId: String, episodeNumber: Int, source: String, ignored: Boolean) = withContext(Dispatchers.IO) {
        context.getSharedPreferences(PREF_NAME, Context.MODE_PRIVATE).edit()
            .putBoolean(ignoredKey(animeId, episodeNumber, source), ignored)
            .apply()
    }

    suspend fun delete(context: Context, animeId: String, episodeNumber: Int, source: String) = withContext(Dispatchers.IO) {
        val prefs = context.getSharedPreferences(PREF_NAME, Context.MODE_PRIVATE)
        val k = key(animeId, episodeNumber, source)
        val paths = prefs.getStringSet(allPathsKey(animeId, episodeNumber.toString(), source), emptySet()).orEmpty() +
            listOfNotNull(prefs.getString(k, null))
        prefs.edit().remove(k).remove(allPathsKey(animeId, episodeNumber.toString(), source)).remove(ignoredKey(animeId, episodeNumber, source))
            .remove(fontPathKey(animeId, source)).remove(fontSourceKey(animeId, source)).apply()
        paths.forEach { File(it).takeIf(File::isFile)?.delete() }
    }
}
